/*

 GAMEMATRIX.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 12 x 24
   Tile set      : Game.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gameMatrixWidth 12
#define gameMatrixHeight 24
#define gameMatrixBank 0

extern unsigned char gameMatrix[];

/* End of GAMEMATRIX.H */
