/*

 GAMETILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 127

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define gameTilesBank 1
/* Start of tile array. */
extern const unsigned char gameTiles[];

/* End of GAMETILES.H */
// Custom defs
#define LEFTARR 	0x55
#define RIGHTARR	0x56
#define LETTER(X)	(X)-'A'+0x57
#define NUMBER(X)	(X)+0x71
/*

 MENU1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Game.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define menu1MapWidth 20
#define menu1MapHeight 18
#define menu1MapBank 1

extern const unsigned char menu1Map[];

/* End of MENU1MAP.H */
/*

 MENUTEXT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 6
   Tile set      : Game.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define menuTextWidth 8
#define menuTextHeight 6
#define menuTextBank 1

extern const unsigned char menuText[];

/* End of MENUTEXT.H */
/*

 GAMEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Game.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gameMapWidth 20
#define gameMapHeight 18
#define gameMapBank 1

extern const unsigned char gameMap[];

/* End of GAMEMAP.H */
/*

 GAMEMATRIX.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 12 x 24
   Tile set      : Game.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define gameMatrixWidth 12
#define gameMatrixHeight 24
#define gameMatrixBank 0

extern const unsigned char gameMatrix[];

/* End of GAMEMATRIX.H */

extern const unsigned char gameOverRow[];
