/*

 MENUTEXT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 8 x 8
   Tile set      : Game.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define menuTextWidth 8
#define menuTextHeight 8
#define menuTextBank 0

extern unsigned char menuText[];

/* End of MENUTEXT.H */
